# espanso configuration file

# This is the default configuration file, change it as you like it
# You can refer to the official documentation:
# https://espanso.org/docs/

# Matches are the substitution rules, when you type the "trigger" string
# it gets replaced by the "replace" string.

# version:      1.0.0
# updated:      Saturday 31 July 2021
# Windows path: C:\Users\garet\AppData\Roaming\espanso
# Linux path:   /home/user/.config/espanso

matches:
          
    # Email

    - trigger: "--@e"
      replace: "gareth@garethjmsaunders.co.uk"

    - trigger: "--@g"
      replace: "garethjmsaunders@gmail.com"

    - trigger: "--@i"
      replace: "isaacjnsaunders@gmail.com"

    - trigger: "--@j"
      replace: "joshuapwsaunders@gmail.com"

    - trigger: "--@r"
      replace: "reubenjmsaunders@gmail.com"

    - trigger: "--@sec"
      replace: "secdigitalcalendar@gmail.com"

    - trigger: "--@w"
      replace: "GarethSaunders@safeguardglobal.com"

    - trigger: "--@195"
      replace: "195metalcds@gmail.com"

    # Gareth

    - trigger: "--address"
      replace: "14 Balcomie Green\nCrail\nANSTRUTHER\nKY10 3UX"

    - trigger: "--add1"
      replace: "14 Balcomie Green"

    - trigger: "--add2"
      replace: "Crail"

    - trigger: "--add3"
      replace: "Anstruther"

    - trigger: "--pc"
      replace: "KY10 3UX"

    - trigger: "--sig"
      replace: "--\n\nGareth J M Saunders\n\n14 Balcomie Green\nCrail\nANSTRUTHER\nKY10 3UX\nFife, Scotland, UK\n\n+44 (0)7732 356123 mobile\n\n+44 (0)1333 451369 home\n\n\ngareth@garethjmsaunders.co.uk\nwww.garethjmsaunders.co.uk"

    - trigger: "--rsig"
      replace: "--\n\nThe Revd Gareth J M Saunders, BD (hons), MTh\n\n14 Balcomie Green\nCrail\nANSTRUTHER\nKY10 3UX\nFife, Scotland, UK\n\n+44 (0)7732 356123 mobile\n\n+44 (0)1333 451369 home\n\n\ngareth@garethjmsaunders.co.uk\nwww.garethjmsaunders.co.uk"    

    - trigger: "--195sig"
      replace: "--\n\nGareth J M Saunders\n195 metal CDs | Independent metal, hardcore, punk and rock reviews from Scotland\n\n195metalcds@gmail.com\nwww.195metalcds.com"

    - trigger: "--gjms"
      replace: "Gareth J M Saunders"

    - trigger: "--gs"
      replace: "Gareth Saunders"    

    - trigger: "--fn"
      replace: "Gareth John McKeith Saunders"

    - trigger: "--rev"
      replace: "The Revd Gareth J M Saunders"    

    - trigger: "--tel"
      replace: "01333 451369"

    - trigger: "--44tel"
      replace: "+44 (0)1333 451369"

    - trigger: "--mob"
      replace: "07732 356123"

    - trigger: "--44mob"
      replace: "+44 (0)7732 356123"

    - trigger: "--mb"
      replace: "07732356123"  

# General

    - trigger: "--abh"
      replace: "Agnes Blackadder Hall"

    - trigger: "--a8c"
      replace: "Automattic"

    - trigger: "creme fraiche"
      replace: "crème fraîche"

    - trigger: "--dct"
      replace: "digital communications team"

    - trigger: "--espanso"
      replace: "C:\\Users\\garet\\AppData\\Roaming\\espanso"

    - trigger: "--nycgb"
      replace: "National Youth Choir of Great Britain"

    - trigger: "--cdreview"
      replace: "## Details\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit.\n\nBandcamp | Encyclopaedia Metallum | Facebook | Instagram | Soundcloud | Tiktok | Twitter | Website | YouTube\n\n## Band\n\n* Vocals, Guitar, Bass, Keyboard, Other, Drums\n\n## Tracks\n\n1. Track 1\n2. Track 2\n\n## Review\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit.\n\n## Conclusion\n\nReview score: %\n\n## Video\n\nLINK_TO_YOUTUBE\n\n## Disclosure\n\nPROMOTER contacted me inviting me to preview BAND_NAME forthcoming album, which I was delighted about.\n\nI have no connections to either PROMOTER or BAND. I’m not being paid to review this. But I did get a free digital copy of the album to review which is pretty cool.\n\nMany thanks to NAME from PROMOTER, and to BAND for continuing to create fresh, exciting GENRE.\n\n## Notes"

    - trigger: "--rji"
      replace: "Reuben, Joshua and Isaac"

    - trigger: "--sec"
      replace: "Scottish Episcopal Church"

    - trigger: "--sta"
      replace: "University of St Andrews"

    - trigger: "--wp"
      replace: "/wp-admin/"

# Spanish

    - trigger: "--!"
      replace: "¡"

    - trigger: "--?"
      replace: "¿"

    - trigger: "a''"
      replace: "á"

    - trigger: "e''"
      replace: "é"

    - trigger: "i''"
      replace: "í"

    - trigger: "n~~"
      replace: "ñ"

    - trigger: "o''"
      replace: "ó"

    - trigger: "u''"
      replace: "ú"

# Typography

    - trigger: "--lorem"
      replace: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed laoreet, metus id sagittis ornare, ex arcu rutrum enim, id porta nulla tortor et urna. Morbi sed quam velit. Curabitur pulvinar risus id suscipit sagittis. Vivamus malesuada turpis quis erat tincidunt commodo. In ac purus sit amet nisi lobortis tempor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent in pulvinar felis, id pharetra magna."

    - trigger: "--1/2"
      replace: "½"

    - trigger: "--1/3"
      replace: "⅓"

    - trigger: "--2/3"
      replace: "⅔"

    - trigger: "--3/4"
      replace: "¾"

    - trigger: "--1/4"
      replace: "¼"

    - trigger: "--deg"
      replace: "°"

    - trigger: "--em"
      replace: "—"

    - trigger: "--en"
      replace: "–"

    - trigger: "--x"
      replace: "×"

    # Dates

    - trigger: "--dddd"
      replace: "{{isodate}}"
      vars:
        - name: isodate
          type: date
          params:
            format: "%Y-%m-%d"

    - trigger: "--today"
      replace: "{{today}}"
      vars:
        - name: today
          type: date
          params:
            format: "%A %d %B %Y"

    - trigger: "--yest"
      replace: "{{yesterday}}"
      vars:
        - name: yesterday
          type: date
          params:
            format: "%A %d %B %Y"
            offset: -86400

    - trigger: "--tom"
      replace: "{{tomorrow}}"
      vars:
        - name: tomorrow
          type: date
          params:
            format: "%A %d %B %Y"
            offset: 86400


    - trigger: "--now"
      replace: "{{now}}"
      vars:
        - name: now
          type: date
          params:
            format: "%A %d %B %Y, %H:%M"

    # Agile

    - trigger: "--agileman"
      replace: "We are uncovering better ways of developing software by doing it and helping others do it. Through this work we have come to value:\n\nIndividuals and interactions over processes and tools\nWorking software over comprehensive documentation\nCustomer collaboration over contract negotiation\nResponding to change over following a plan\n\nThat is, while there is value in the items on the right, we value the items on the left more."

    - trigger: "--boscard"
      replace: "background, objectives, scope, constraints, assumptions, risks and deliverables"

    - trigger: "--pestle"
      replace: "political, economic, socio-cultural, technological, legal, and environmental"

    - trigger: "--po"
      replace: "product owner"

    - trigger: "--sos"
      replace: "scrum of scrums"

    - trigger: "--scrumvalues"
      replace: "commitment, courage, focus, openness, respect"

    - trigger: "--smast"
      replace: "scrum master"

    - trigger: "--smart"
      replace: "specific, measurable, achievable, relevant and time-bound"

    - trigger: "--tsos"
      replace: "technical scrum of scrums"


    # Emoji

    - trigger: "--;)"
      replace: "😉"

    - trigger: "--cry"
      replace: "😢"

    - trigger: "--weep"
      replace: "😭"      

    - trigger: "--lol"
      replace: "😂"

    - trigger: "--rofl"
      replace: "🤣"